name: CI
on: [push]
jobs:
  build:
    strategy:
      matrix:
        c-compiler: [gcc, clang]
        os: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          - os: macos-latest
            c-compiler: gcc
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install ubuntu dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install valgrind
        sudo apt-get install python3-enchant
    - name: Install macos dependencies
      if: matrix.os == 'macos-latest'
      run: brew install enchant
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt
    - name: Make all binaries with ${{ matrix.c-compiler }}
      env:
          CC: ${{ matrix.c-compiler }}
      run: make all
      shell: bash
    - name: Run all tests with ${{ matrix.c-compiler }}
      env:
          CC: ${{ matrix.c-compiler }}
      run: ./test.sh
      shell: bash
