name: CI
on: [push]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        c-compiler: [gcc, clang, 'gcc -m32']
        os: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          - os: windows-latest
            c-compiler: clang
          - os: windows-latest
            c-compiler: 'gcc -m32'
          - os: macos-latest
            c-compiler: 'gcc -m32'
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      if: matrix.os != 'windows-latest'
      with:
        python-version: '3.x'
    - name: Setup windows Python
      uses: actions/setup-python@v1
      if: matrix.os == 'windows-latest'
      with:
        python-version: '3.6'
        architecture: 'x86'
    - name: Install ubuntu dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install valgrind
        sudo apt-get install gcc-multilib
        sudo apt-get install python3-enchant
    - name: Install macos dependencies
      if: matrix.os == 'macos-latest'
      run: brew install enchant
    - name: Install windows dependencies
      if: matrix.os == 'windows-latest'
      run: choco install llvm
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt
    - name: Make all binaries with ${{ matrix.c-compiler }}
      env:
          CC: ${{ matrix.c-compiler }}
      run: make all
    - name: Run all tests with ${{ matrix.c-compiler }}
      env:
          CC: ${{ matrix.c-compiler }}
      run: ./test.sh
      shell: bash
