name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        c-compiler: [gcc, clang]
    steps:
    - uses: actions/checkout@v1
    - name: Install package dependencies
      run: |
        sudo apt-get update
        sudo apt-get install valgrind
        sudo apt-get install python3-enchant
        sudo apt-get install python3-sphinx
    - name: Install Python dependencies
      run: |
        pip3 install --user setuptools wheel virtualenv
        pip3 install --user -r docs/requirements.txt
        pip3 uninstall -y sphinx
        pip3 install --user sphinx==1.6.7
    - name: Make all binaries with ${{ matrix.c-compiler }}
      env:
          CC: ${{ matrix.c-compiler }}
      run: make all
    - name: Run all tests with ${{ matrix.c-compiler }}
      env:
          CC: ${{ matrix.c-compiler }}
      run: ./test.sh
